default: &default
  password: 'Josuemagico1'


  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kata_07_rejoj_checador_equipo_04_k07_development

test:
  <<: *default
  database: kata_07_rejoj_checador_equipo_04_k07_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
